# SPDX-FileCopyrightText: 2025 SURF B.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Check deps for vulnerabilities

on:
  push:
    branches: ["*"]
    tags: ["*"]
  schedule:
    - cron: '0 1 * * 1,2,3,4,5' # every workday

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-clojure-${{ hashFiles('**/project.clj') }}"

    - run: |
        .github/workflows/install-binaries.sh
        echo "${PWD}/bin" >> $GITHUB_PATH

    - env:
        NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}
      if: ${{ env.NVD_API_TOKEN == '' }}
      run: echo "NVD_API_TOKEN secret is empty"; exit 1

    - env:
        CLJ_WATSON_NVD_API_KEY: ${{ secrets.NVD_API_TOKEN }}
      run: make watson
