# SPDX-FileCopyrightText: 2026 SURF B.V.
#
# SPDX-License-Identifier: Apache-2.0

name: Run outdated check

on: workflow_call

jobs:
  outdated:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: jomco/clojure-action@fae8cb45f4bf09bb63cdcbe8277f14d9243bf609 # v0
      with: { m2-cache-key: m2-outdated }

    - name: Run make outdated
      run: |
        make outdated
