# SPDX-FileCopyrightText: 2024 SURF B.V.
# SPDX-FileContributor: Joost Diepenmaat
#
# SPDX-License-Identifier: Apache-2.0

name: Run tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with: { path: "~/.m2", key: "${{ runner.os }}-${{ hashFiles('deps.edn') }}-m2" }

    - run: |
        .github/workflows/install-binaries.sh
        echo "${PWD}/bin" >> $GITHUB_PATH

      
    - name: run tests
      run: make check
