# SPDX-FileCopyrightText: 2024 SURF B.V.
# SPDX-FileContributor: Joost Diepenmaat
#
# SPDX-License-Identifier: Apache-2.0

name: Run tests

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: jomco/clojure-action@v0

    - name: run tests
      run: make check
